import { describe, expect, it } from 'vitest'
import { escAttr, escJsonForScript, escText } from '@/lib/identity/escape'

/**
 * §12.12.7 — the record document is generated by string templating, so these
 * three functions are the whole security boundary of a file the reader hands to
 * an employer. The payload below is the one that matters: a name that closes a
 * script element and opens an image with a handler on it.
 */
const PAYLOAD = '</script><img src=x onerror=alert(1)>'

describe('escText', () => {
  it('escapes the two characters a text node can be escaped from', () => {
    expect(escText('a & b')).toBe('a &amp; b')
    expect(escText('a < b')).toBe('a &lt; b')
  })

  it('leaves > and both quotes alone — a text node cannot be left by them', () => {
    expect(escText('a > b')).toBe('a > b')
    expect(escText(`"'`)).toBe(`"'`)
  })

  it('escapes in one pass, so & is never double-encoded out of order', () => {
    // '<' → '&lt;' must not then have its own '&' re-escaped.
    expect(escText('<')).toBe('&lt;')
    // An already-encoded entity in the input is data, and its & is escaped once.
    expect(escText('&amp;')).toBe('&amp;amp;')
  })

  it('neutralises the payload: no < survives, so no tag can be parsed', () => {
    const out = escText(PAYLOAD)
    expect(out).not.toContain('<')
    expect(out.toLowerCase()).not.toContain('</script')
    expect(out).toBe('&lt;/script>&lt;img src=x onerror=alert(1)>')
  })

  it('passes non-ASCII through untouched — this is not a sanitiser', () => {
    expect(escText('İpek · क्षमा · 田中 · 👩‍🔬')).toBe('İpek · क्षमा · 田中 · 👩‍🔬')
  })

  it('returns the empty string unchanged', () => {
    expect(escText('')).toBe('')
  })
})

describe('escAttr', () => {
  it('escapes all five characters', () => {
    expect(escAttr(`& < > " '`)).toBe('&amp; &lt; &gt; &quot; &#39;')
  })

  it('closes a double-quoted attribute value against a handler injection', () => {
    const out = escAttr('" onerror="alert(1)')
    expect(out).not.toContain('"')
    expect(out).toBe('&quot; onerror=&quot;alert(1)')
  })

  it('closes a single-quoted attribute value too', () => {
    const out = escAttr(`' onerror='alert(1)`)
    expect(out).not.toContain("'")
  })

  it('neutralises the payload in an attribute', () => {
    const out = escAttr(PAYLOAD)
    expect(out).not.toContain('<')
    expect(out).not.toContain('>')
    expect(out.toLowerCase()).not.toContain('</script')
  })

  it('escapes in one pass', () => {
    expect(escAttr('<')).toBe('&lt;')
  })
})

describe('escJsonForScript', () => {
  it('escapes < as the JSON-valid \\u003c, never as an entity', () => {
    expect(escJsonForScript('<')).toBe('"\\u003c"')
    // A data block is raw text: character references are NOT decoded in it, so
    // '&lt;' would be four literal characters inside the parsed string.
    expect(escJsonForScript('<')).not.toContain('&lt;')
  })

  it('leaves no < anywhere in the output', () => {
    const out = escJsonForScript({ name: PAYLOAD, note: '<!-- <script> -->' })
    expect(out).not.toContain('<')
  })

  it('kills all three sequences the HTML spec forbids in script text', () => {
    const out = escJsonForScript(['<!--', '<script', '</script', '</SCRIPT >']).toLowerCase()
    expect(out).not.toContain('<!--')
    expect(out).not.toContain('<script')
    expect(out).not.toContain('</script')
  })

  it('round-trips through JSON.parse — the escape is inside JSON, not around it', () => {
    const value = { name: PAYLOAD, marks: ['<a>', '&', '"'], n: 3, ok: true, nil: null }
    expect(JSON.parse(escJsonForScript(value))).toEqual(value)
  })

  it('does not escape & — the data block is raw text and & is literal there', () => {
    expect(escJsonForScript('a & b')).toBe('"a & b"')
  })

  it('emits null rather than the non-JSON literal "undefined"', () => {
    // JSON.stringify(undefined) is undefined. Writing that word into the block
    // would make the document's own JSON.parse throw and blank the page.
    expect(escJsonForScript(undefined)).toBe('null')
    expect(() => JSON.parse(escJsonForScript(undefined))).not.toThrow()
    expect(escJsonForScript(() => 1)).toBe('null')
  })

  it('survives a name made entirely of the payload, nested deep', () => {
    const value = { sheets: { 'fundamentals/llms': { note: PAYLOAD } } }
    const out = escJsonForScript(value)
    expect(out.toLowerCase()).not.toContain('</script')
    expect(JSON.parse(out)).toEqual(value)
  })
})
