#!/usr/bin/env node
/**
 * Generate `src/app/lokum-modules.css` from `mini-courses/curriculum.yaml`.
 *
 *   node scripts/curriculum-css.mjs           write the file
 *   node scripts/curriculum-css.mjs --check   exit 1 if the file is out of date
 *
 * ## Why this is generated and the rest of `lokum.css` is not
 *
 * Channel A (§12.2) reveals a signed state from a class the boot script stamps
 * on `<html>` before first paint, so every state rule is a selector matching
 * that class against a descendant's attribute:
 *
 *   html.hl-signed-13 .hl-seg[data-module="13"] { … }
 *
 * **CSS has no operator that compares a root class to a descendant's attribute
 * value.** There is no `:has()`, `attr()` or custom-property trick that
 * expresses "the number in the class equals the number in the attribute": the
 * two live in different places in the selector and CSS cannot relate them. So
 * the list has to be enumerated once per module, and enumeration is inherent to
 * the design rather than an accident of it.
 *
 * What is an accident is enumerating it BY HAND. Three lists, 61 selectors, all
 * keyed on a number the curriculum now computes:
 *
 *   A  every module      the segment fills with its category hue
 *   B  drawn modules     the path step says SIGNED OFF
 *   C  drawn modules     the same segment, inside `forced-colors: active`,
 *                        filled with a system colour so the state survives
 *                        with no hue at all
 *
 * B and C stop at the drawn sheets deliberately. A draft sheet has no sign-off
 * control (§12.4.1), so `hl-signed-<n>` can never be stamped for one, and
 * writing the rule anyway would state that it could. A is the whole set,
 * because a draft segment is still drawn (dashed, unfillable) and keeping the
 * list uniform costs nothing.
 *
 * ## Why the output is committed
 *
 * `prebuild` regenerates it, but vitest and playwright do not run `prebuild`.
 * A gitignored generated stylesheet would therefore be absent in exactly the
 * two places that check it. It is committed, and
 * `tests/unit/color/category-css.test.ts` runs this generator and asserts the
 * committed file matches, so it cannot go stale without something going red.
 */

import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import yaml from 'js-yaml'

const ROOT = path.resolve(import.meta.dirname, '..')
const SOURCE = path.join(ROOT, 'mini-courses', 'curriculum.yaml')
export const OUTPUT = path.join(ROOT, 'src', 'app', 'lokum-modules.css')

/** Every module's number and whether it is drawn, in curriculum order. */
function modules() {
  const doc = yaml.safeLoad(fs.readFileSync(SOURCE, 'utf8'))
  const found = []
  for (const category of doc.categories) {
    for (const entry of category.modules) {
      found.push({ module: found.length + 1, drawn: (entry.status ?? 'draft') === 'ready' })
    }
  }
  return found
}

/**
 * One selector list, padded so the two numbers in each line sit in a column.
 * The alignment is what makes a mismatched pair visible to a reader, and
 * `category-css.test.ts` checks for one mechanically as well.
 */
function selectors(numbers, shape) {
  const width = String(Math.max(...numbers)).length
  return numbers
    .map((n) => `  ${shape(String(n).padEnd(width), n)},`)
    .join('\n')
    .replace(/,$/, ' {')
}

export function render() {
  const all = modules()
  const every = all.map((m) => m.module)
  const drawn = all.filter((m) => m.drawn).map((m) => m.module)

  return `/* GENERATED by scripts/curriculum-css.mjs from mini-courses/curriculum.yaml.
   Do not edit. Run \`node scripts/curriculum-css.mjs\` after changing the
   curriculum, which \`npm run build\` does for you.

   Why these lists are enumerated at all, and why only these three: see the
   docblock at the top of the generator. Short version: channel A matches a
   class on <html> against an attribute on a descendant, and CSS has no
   operator that compares the two, so there is one selector per module and
   there has to be. What the generator removes is writing them out by hand,
   keyed on a number the curriculum computes.

   ${every.length} modules, ${drawn.length} of them drawn. */

@layer components {
  /* A. Every module. The segment fills with its own category's hue.
     \`--hl-cat\` was resolved by the carrier in lokum.css from the segment's own
     \`data-cat\`, so the category never appears here. */
${selectors(every, (pad, n) => `html.hl-signed-${pad} .hl-seg[data-module="${n}"]`)}
    background: var(--hl-cat);
    border-color: var(--hl-cat);
  }

  /* B. The drawn modules only. A step the reader has signed off says so in
     words, in the accent pen. A draft sheet has no sign-off control at all
     (§12.4.1), so no selector for one could ever match, and writing one would
     state that it could. */
${selectors(drawn, (pad, n) => `html.hl-signed-${pad} .hl-step[data-module="${n}"] .hl-step-tick`)}
    display: inline;
    color: var(--color-accent-ink);   /* T2 — accent as TEXT is \`-ink\` only. */
  }
}

/* Forced colours — §13.1.4. Every hue is dropped, and the drawing must still
   read. A signed segment is filled with the system colour, so "signed off"
   survives as a difference in FILL rather than in hue.
   \`tests/e2e/colour-not-alone.spec.ts\` loads a signed record under
   \`forced-colors: active\` and asserts each surface still reports its state. */
@media (forced-colors: active) {
  /* C. The drawn modules, for the same reason B stops there. */
${selectors(drawn, (pad, n) => `html.hl-signed-${pad} .hl-seg[data-module="${n}"]`)}
    /* Filled with the system colour, so "signed off" is still a filled cell
       against an empty one: a difference in fill, not in hue. \`forced-color-
       adjust\` is already \`none\` on \`.hl-seg\` in lokum.css's own block. */
    background: CanvasText;
    border-color: CanvasText;
  }
}
`
}

// Run as a script, it writes or checks. Imported (which is how the test reads
// `render()`), it does nothing at all: a module that writes a file on import
// would make the test it feeds pass by rewriting its own subject.
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  const css = render()
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : ''
    if (current !== css) {
      console.error('lokum-modules.css is out of date. Run `node scripts/curriculum-css.mjs`.')
      process.exit(1)
    }
    console.log('lokum-modules.css is up to date.')
  } else {
    fs.writeFileSync(OUTPUT, css)
    console.log(`curriculum-css: wrote ${path.relative(ROOT, OUTPUT)}`)
  }
}
