#!/usr/bin/env node
/**
 * Generate `src/app/lokum-modules.css` from `mini-courses/curriculum.yaml`.
 *
 *   node scripts/curriculum-css.mjs           write the file
 *   node scripts/curriculum-css.mjs --check   exit 1 if the file is out of date
 *
 * ## Why this is generated and the rest of the stylesheets are not
 *
 * Channel A (§12.2) reveals a signed state from a class the boot script stamps
 * on `<html>` before first paint, so every state rule is a selector matching
 * that class against a descendant's attribute:
 *
 *   html.hl-signed-13 .bz-seg[data-module="13"] { … }
 *
 * **CSS has no operator that compares a root class to a descendant's attribute
 * value.** There is no `:has()`, `attr()` or custom-property trick that
 * expresses "the number in the class equals the number in the attribute": the
 * two live in different places in the selector and CSS cannot relate them. So
 * the list has to be enumerated once per module, and enumeration is inherent to
 * the design rather than an accident of it.
 *
 * What is an accident is enumerating it BY HAND. Five lists, all keyed on a
 * number the curriculum now computes:
 *
 *   A  every module      the segment fills with its category hue
 *   B  drawn modules     the path step says SIGNED OFF
 *   C  drawn modules     the same segment, inside `forced-colors: active`,
 *                        filled with a system colour so the state survives
 *                        with no hue at all
 *   D  drawn modules     M10 — the curriculum rail's completion tick, a 17px
 *                        filled disc revealed on the row of a module the
 *                        reader has completed
 *   E  drawn modules     M13/M14 — completion control C's tick, the same disc
 *                        on the same channel, inside the toggle that sets it
 *
 * B, C, D and E stop at the drawn sheets deliberately. A draft sheet has no
 * completion control (§12.4.1), so `hl-signed-<n>` can never be stamped for
 * one, and writing the rule anyway would state that it could. A is the whole
 * set, because a draft segment is still drawn (dashed, unfillable) and keeping
 * the list uniform costs nothing.
 *
 * D and E need no forced-colours twin, and that is the one asymmetry worth
 * naming: the disc is revealed by `display`, and `display` survives a
 * forced-colours theme untouched. Its fill and its check take the system
 * colours from one unconditional rule in the surface's own stylesheet, so
 * nothing per-module has to be repeated.
 *
 * **E is why control C is a control and not a readout.** A completion the
 * reader can set from a list of thirty-three has to be RIGHT in frame one for
 * the modules already completed, or the page flashes an empty record at exactly
 * the reader who has one; a tick that arrives with React cannot be. So the
 * button's mark is channel A like every other mark on the site, and only its
 * `aria-pressed` — an attribute, not a picture — waits for the store.
 *
 * ## Why the output is committed
 *
 * `prebuild` regenerates it, but vitest and playwright do not run `prebuild`.
 * A gitignored generated stylesheet would therefore be absent in exactly the
 * two places that check it. It is committed, and
 * `tests/unit/color/category-css.test.ts` runs this generator and asserts the
 * committed file matches, so it cannot go stale without something going red.
 */

import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import yaml from 'js-yaml'

const ROOT = path.resolve(import.meta.dirname, '..')
const SOURCE = path.join(ROOT, 'mini-courses', 'curriculum.yaml')
export const OUTPUT = path.join(ROOT, 'src', 'app', 'lokum-modules.css')

/** Every module's number and whether it is drawn, in curriculum order. */
function modules() {
  const doc = yaml.safeLoad(fs.readFileSync(SOURCE, 'utf8'))
  const found = []
  for (const category of doc.categories) {
    for (const entry of category.modules) {
      found.push({ module: found.length + 1, drawn: (entry.status ?? 'draft') === 'ready' })
    }
  }
  return found
}

/**
 * One selector list, padded so the two numbers in each line sit in a column.
 * The alignment is what makes a mismatched pair visible to a reader, and
 * `category-css.test.ts` checks for one mechanically as well.
 */
function selectors(numbers, shape) {
  const width = String(Math.max(...numbers)).length
  return numbers
    .map((n) => `  ${shape(String(n).padEnd(width), n)},`)
    .join('\n')
    .replace(/,$/, ' {')
}

export function render() {
  const all = modules()
  const every = all.map((m) => m.module)
  const drawn = all.filter((m) => m.drawn).map((m) => m.module)

  return `/* GENERATED by scripts/curriculum-css.mjs from mini-courses/curriculum.yaml.
   Do not edit. Run \`node scripts/curriculum-css.mjs\` after changing the
   curriculum, which \`npm run build\` does for you.

   Why these lists are enumerated at all, and why only these five: see the
   docblock at the top of the generator. Short version: channel A matches a
   class on <html> against an attribute on a descendant, and CSS has no
   operator that compares the two, so there is one selector per module and
   there has to be. What the generator removes is writing them out by hand,
   keyed on a number the curriculum computes.

   ${every.length} modules, ${drawn.length} of them drawn. */

@layer components {
  /* A. Every module. The segment fills with its own category's hue.
     \`--bz-cat\` is resolved by the carrier from the segment's own \`data-cat\`,
     so the category never appears here. M16 owes that binding to whichever
     surface stylesheet draws the segment. */
${selectors(every, (pad, n) => `html.hl-signed-${pad} .bz-seg[data-module="${n}"]`)}
    background: var(--bz-cat);
    border-color: var(--bz-cat);
  }

  /* B. The drawn modules only. A step the reader has signed off says so in
     words, in the accent pen. A draft sheet has no sign-off control at all
     (§12.4.1), so no selector for one could ever match, and writing one would
     state that it could. */
${selectors(drawn, (pad, n) => `html.hl-signed-${pad} .bz-step[data-module="${n}"] .bz-step-tick`)}
    display: inline;
    color: var(--color-accent-ink);   /* T2 — accent as TEXT is \`-ink\` only. */
  }

  /* D. M10 — the curriculum rail's tick, for the drawn modules only. The mark
     is a 17px teal disc with a white check and an \`sr-only\` word inside it, so
     revealing it reveals the shape, the fill and the statement together and
     colour is never the only carrier. The rail's own stylesheet holds its
     geometry. */
${selectors(drawn, (pad, n) => `html.hl-signed-${pad} .bz-mod[data-module="${n}"] .bz-mod-mark`)}
    display: inline-flex;
  }

  /* E. M13/M14 — completion control C's tick, for the drawn modules only. The
     disc sits inside the button that SETS the completion, so the reader's own
     state is right in frame one on a page that lists every module.
     The completion surface's own stylesheet holds its geometry. */
${selectors(drawn, (pad, n) => `html.hl-signed-${pad} .bz-cmod[data-module="${n}"] .bz-cmod-mark`)}
    display: inline-flex;
  }

  /* E2. The word that says what E's disc means, on the same channel and for the
     same modules, so the picture and the sentence cannot come apart.
     It is a SEPARATE element and a separate class rather than an \`sr-only\`
     span inside the button, for two reasons. \`aria-label\` on the button
     replaces its contents for naming, so a word inside it is never announced
     at all — which is what made \`aria-pressed\` the only statement of the
     state an assistive technology got, on channel B, permanently contradicting
     this disc with scripts refused. And giving it E's own class instead made
     \`.bz-cmod-mark\` match two elements per row, which is a strict-mode
     violation in every locator that reads the tick. */
${selectors(drawn, (pad, n) => `html.hl-signed-${pad} .bz-cmod[data-module="${n}"] .bz-cmod-said`)}
    display: inline;
  }
}

/* Forced colours — §13.1.4. Every hue is dropped, and the drawing must still
   read. A signed segment is filled with the system colour, so "signed off"
   survives as a difference in FILL rather than in hue.
   \`tests/e2e/colour-not-alone.spec.ts\` loads a signed record under
   \`forced-colors: active\` and asserts each surface still reports its state. */
@media (forced-colors: active) {
  /* C. The drawn modules, for the same reason B stops there. */
${selectors(drawn, (pad, n) => `html.hl-signed-${pad} .bz-seg[data-module="${n}"]`)}
    /* Filled with the system colour, so "signed off" is still a filled cell
       against an empty one: a difference in fill, not in hue. \`forced-color-
       adjust\` is set to \`none\` on \`.bz-seg\` where that segment is drawn. */
    background: CanvasText;
    border-color: CanvasText;
  }
}
`
}

// Run as a script, it writes or checks. Imported (which is how the test reads
// `render()`), it does nothing at all: a module that writes a file on import
// would make the test it feeds pass by rewriting its own subject.
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  const css = render()
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : ''
    if (current !== css) {
      console.error('lokum-modules.css is out of date. Run `node scripts/curriculum-css.mjs`.')
      process.exit(1)
    }
    console.log('lokum-modules.css is up to date.')
  } else {
    fs.writeFileSync(OUTPUT, css)
    console.log(`curriculum-css: wrote ${path.relative(ROOT, OUTPUT)}`)
  }
}
